### ISSUE TITLE
[BUG REPORT] Hyperlink not working

### ISSUE THREAD

**Issue by KendallDoesCoding** [KendallDoesCoding/portfolio#15]
I cant use a hyperlink for some reason as it doesnt show up. I need to fix the issue and link the subscribe for updates url via a hyperlink to the here text.

@TechStudent11 can you please help, the hyperlink text doesnt show up unless I highlight/select the text on the website.

**Comment by TechStudent11** [comment]
ohhh that's what you want

**Comment by KendallDoesCoding** [comment]
> ohhh that's what you want

Yes.
