### ISSUE TITLE
[FEAT] Improve Design of Projects section

### ISSUE THREAD

**Issue by KendallDoesCoding** [KendallDoesCoding/portfolio#29]
The design of the projects section can be improved a bit.

**Comment by Osauyi** [comment]
HI
beginner here, what  kind design  of design are you looking for?

**Comment by KendallDoesCoding** [comment]
> [Osauyi](/Osauyi)

any improvement to the current design would be perfect. I don't really have an idea in mind.

**Comment by Osauyi** [comment]
they are a lot of unnecessary height, and don't know why clicking  "inspect" scatters every thing, but anyway am not yet done and what i did its not noticeable .. : - )

**Comment by Osauyi** [comment]
#30

**Comment by karthiknadar1204** [comment]
i would like to work on this issue,could you please assign it to me

**Comment by KendallDoesCoding** [comment]
> i would like to work on this issue,could you please assign it to me

Sure

**Comment by KendallDoesCoding** [comment]
@karthiknadar1204 - @Osauyi did part of the changes, if you can improve it further, go ahead, otherwise will close this issue.

**Comment by KendallDoesCoding** [comment]
Awaiting your reply @karthiknadar1204!

**Comment by karthiknadar1204** [comment]
Will share update by Wednesday,about all the changes that can be applied and merge a request by Thursday.

Apologies for the inconvenience caused.

**Comment by KendallDoesCoding** [comment]
> Will share update by Wednesday,about all the changes that can be applied and merge a request by Thursday.
> 
> Apologies for the inconvenience caused.

Bro, no worries. I just wanted to know if you will work on this further as @Osauyi has already made changes. Will assign you.

No need to be sorry. Thanks a lot for your help, I really appreciate you.

**Comment by karthiknadar1204** [comment]
@KendallDoesCoding ,have reviewed the site, couldn't find any necessary changes to be made but i do think we have an issue,
Well on the navbar clicking on "About Me" and "Projects" scrolls down smoothly but on clicking on "Contact us",the link changes but we are not being re-directed to any other page, there must be an issue with the Route. That is all from my side, if you deem it to be an issue, i would like to work on it.

**Comment by KendallDoesCoding** [comment]
> @KendallDoesCoding ,have reviewed the site, couldn't find any necessary changes to be made but i do think we have an issue, Well on the navbar clicking on "About Me" and "Projects" scrolls down smoothly but on clicking on "Contact us",the link changes but we are not being re-directed to any other page, there must be an issue with the Route. That is all from my side, if you deem it to be an issue, i would like to work on it.

Well, that's because I updated the contact section recently, and just forgot to add the id.

This issue was created to update the design of the Projects, cause people gave me feedback that it doesn't look too good and even I thought so.

@Osauyi made it look much better, if you can improve the design of the projects section then go ahead, or I'll close the issue.

Thanks @karthiknadar1204!!

**Comment by karthiknadar1204** [comment]
I see no issues with the design anymore , Thank you so much

**Comment by KendallDoesCoding** [comment]
> I see no issues with the design anymore , Thank you so much

Thanks!
