### ISSUE TITLE
[FEAT] Make font size less on Mobile

### ISSUE THREAD

**Issue by KendallDoesCoding** [KendallDoesCoding/portfolio#36]
Make the website, mobile responsive using CSS (media tag)

**Comment by pushkaraj2007** [comment]
Hey @KendallDoesCoding 

I would like to work on this issue, can you please assign me?

**Comment by KendallDoesCoding** [comment]
> Hey @KendallDoesCoding
> 
> I would like to work on this issue, can you please assign me?

Sure!

**Comment by pushkaraj2007** [comment]
Can you explain a bit more, what is the exact section you want to make responsive?

Because I checked the site and it's looking fine.

**Comment by KendallDoesCoding** [comment]
> Can you explain a bit more, what is the exact section you want to make responsive?
> 
> Because I checked the site and it's looking fine.

- About Us
- Reach Out The Kendall
- Footer

There is too much margin too, that the user will have to swipe, I just want it to come in one go.

**Comment by pushkaraj2007** [comment]
@KendallDoesCoding 

Sure, I'll do it fast and quick
