### ISSUE TITLE
Navbar is not responsive

### ISSUE THREAD

**Issue by pushkaraj2007** [KendallDoesCoding/portfolio#38]
**Describe the bug**
Navbar is not responsive for small-screen devices

**To Reproduce**
1. Go to 'website on small screen devices'
2. Click on the 'navbar icon'
3. See the error

**Expected behavior**
Navbar should be responsive on small-screen devices like mobile.

**Screenshots**
![image](https://user-images.githubusercontent.com/107422421/233680791-f0c4a79e-1633-4852-95b7-fcdaf0cc7faa.png)

**Comment by KendallDoesCoding** [comment]
Can you work on this and make one PR for #36 and this?

**Comment by pushkaraj2007** [comment]
@KendallDoesCoding 

It will be great to differentiate different issues in different PRs as it is a good practice in open-source.

And sure, I'll work on this issue you may assign me.

**Comment by KendallDoesCoding** [comment]
> @KendallDoesCoding
> 
> It will be great to differentiate different issues in different PRs as it is a good practice in open-source.
> 
> And sure, I'll work on this issue you may assign me.

Ok.
